# Generated by Django 5.2.4 on 2025-07-07 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PoliagentX', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Indicator',
        ),
        migrations.AlterModelOptions(
            name='governmentindicator',
            options={'ordering': ['indicator_label'], 'verbose_name': 'Government Indicator', 'verbose_name_plural': 'Government Indicators'},
        ),
        migrations.RemoveField(
            model_name='governmentindicator',
            name='indicator_type',
        ),
        migrations.AlterField(
            model_name='governmentindicator',
            name='instrumental',
            field=models.CharField(choices=[('1', '0'), ('1', '1')], max_length=10),
        ),
        migrations.AlterField(
            model_name='governmentindicator',
            name='monitoring',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='governmentindicator',
            name='rule_of_law',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='governmentindicator',
            name='source_file',
            field=models.ForeignKey(blank=True, help_text='EXCEL file from which this indicator was sourced.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='PoliagentX.excelfileupload'),
        ),
    ]
