# Generated by Django 5.2.4 on 2025-08-08 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PoliagentX', '0002_delete_indicator_alter_governmentindicator_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottleneckanalysis',
            name='workflow_run',
        ),
        migrations.RemoveField(
            model_name='workflowrun',
            name='indicators_file',
        ),
        migrations.RemoveField(
            model_name='governmentindicator',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='interdependency',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='workflowrun',
            name='expenditure_file',
        ),
        migrations.RemoveField(
            model_name='governmentexpenditure',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='interdependency',
            name='from_expenditure',
        ),
        migrations.RemoveField(
            model_name='interdependency',
            name='to_expenditure',
        ),
        migrations.RemoveField(
            model_name='interdependency',
            name='to_indicator',
        ),
        migrations.RemoveField(
            model_name='interdependency',
            name='from_indicator',
        ),
        migrations.DeleteModel(
            name='AnalysisResult',
        ),
        migrations.DeleteModel(
            name='BottleneckAnalysis',
        ),
        migrations.DeleteModel(
            name='WorkflowRun',
        ),
        migrations.DeleteModel(
            name='EXCELFileUpload',
        ),
        migrations.DeleteModel(
            name='GovernmentExpenditure',
        ),
        migrations.DeleteModel(
            name='GovernmentIndicator',
        ),
        migrations.DeleteModel(
            name='Interdependency',
        ),
    ]
